import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import SideBar from "@/components/SideBar";
import ContextProvider from "@/providers/ContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Web App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body suppressHydrationWarning={true}>
				<ContextProvider>
					<>
						<Navbar />
						<div className="flex relative text-[28px]">
							<SideBar />
							{children}
						</div>
					</>
				</ContextProvider>
			</body>
		</html>
	);
}
